### ISSUE TITLE
Always empty result in certain webpack / babel configs

### ISSUE THREAD

**Issue by pixelplanetdev** [ibezkrovnyi/image-quantization#95]
In some webpack / babel configurations image-q quantize always outputs an image with only rgba: 0 Points.

Follow up to #93

I created a test repository to recreate the bug
https://github.com/pixelplanetdev/image-q-bugtest
its currently uploaded to
https://storage.pixelplanet.fun/dist/

**Comment by ibezkrovnyi** [comment]
Thank you for your efforts and great minimal reproduceable project - actually I found a bug. This happens because of breaking change in ecmascript standard that is described here:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier

### now
```ts
export class AbstractEuclidean extends AbstractDistanceCalculator {
    _kR;
    _kG;
    _kB;
    _kA;
    calculateRaw(r1, g1, b1, a1, r2, g2, b2, a2) {
        const dR = r2 - r1;
        const dG = g2 - g1;
        const dB = b2 - b1;
        const dA = a2 - a1;
        return Math.sqrt(this._kR * dR * dR +
            this._kG * dG * dG +
            this._kB * dB * dB +
            this._kA * dA * dA);
    }
}
```

Which is converted by babel into (pseudo-code):
```ts
class AbstractEuclidean extends AbstractDistanceCalculator {
  constructor() {
    super(...arguments); // here this._setDefaults is called, which is defined in child class
    _kR = undefined;
    _kG = undefined;
    _kB = undefined;
    _kA = undefined;
  }
}
```

**Fix: **add `declare` before every `_k*` property in AbstractEuclidean class

### Fixed version renders:
![image](https://user-images.githubusercontent.com/1188919/148385663-4b492c17-24a9-4873-b044-c08875b500ba.png)

**Comment by ibezkrovnyi** [comment]
upd: bug is in esm build (tsc) only, while umd build (webpack + esbuild) is ok

**Comment by ibezkrovnyi** [comment]
@pixelplanetdev can I use https://github.com/pixelplanetdev/image-q-bugtest as test case in image-q ?

**Comment by pixelplanetdev** [comment]
@ibezkrovnyi of course, but i will archive the repository when its not needed anymore.
Thanks for your work.
